variable "aws_profile_name"     { }
#variable "iam_instance_profile" { }
variable "instance_type"        { }
variable "key_name"             { }
variable "key_private_file"     { }
variable "key_public_file"      { }
variable "region"               { }
variable "ssh_cdir_block"       { }
variable "ssh_user"             { }
variable "vpc_cidr"             { }
variable "vpc_name"             { }
