- name: install yum utilities
  yum:
    state: latest
    name: yum-utils
  vars:
    ansible_python_interpreter: /usr/bin/python

- name: add docker repo
  command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

- name: install docker packages
  yum:
    state: latest
    name: 
    - docker-ce 
    - docker-ce-cli 
    - containerd.io
  vars:
    ansible_python_interpreter: /usr/bin/python

- name: Start and enable docker
  systemd:
    enabled: yes
    name: docker
    state: started

- name: Ensure group "docker" exists
  group:
    name: docker
    state: present

- name: adding existing user '{{ user }}' to group docker
  user:
    name: '{{ ssh_user }}'
    groups: docker
    append: yes

- name: get kernel name
  command: uname -s
  register: kernel_name

- name: get machine name
  command: uname -m
  register: machine_name

- name: Download docker-compose
  get_url:
    dest: /usr/local/bin/docker-compose
    url: "https://github.com/docker/compose/releases/latest/download/docker-compose-{{kernel_name.stdout}}-{{machine_name.stdout}}"
    mode: 0755
  vars:
    ansible_python_interpreter: /usr/bin/python
