---
- hosts: all
  gather_facts: false
  become: yes

  vars:
    ansible_python_interpreter: /bin/python3

  tasks:

    - name: include data volume mount tasks.
      import_tasks: playbook.mount-data-volume.yml

    - name: include docker tasks.
      import_tasks: playbook.docker.yml
