#!/bin/bash

rm -f ./inventory ./ssh-to-server.sh

export TF_IGNORE=trace
export TF_IN_AUTOMATION=true
export TF_LOG=TRACE
export TF_LOG_PATH="ylog-tf-apply-$(date "+%Y-%m-%d_%H:%M").log"

source .envrc

terraform init
terraform workspace new dev
terraform workspace select dev
terraform init -input=false
terraform plan -out=tfplan -input=false
time terraform apply -input=false --auto-approve tfplan

ls -ltr ylog-tf-apply*.log | tail -n 1
